name:                advent-of-code-y2021
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:      src

executables:
  d01:
    source-dirs: exe
    main: d01.hs
    dependencies: advent-of-code-y2021
  d02:
    source-dirs: exe
    main: d02.hs
    dependencies: advent-of-code-y2021
