name:                advent-of-code-y2021
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:      src
  dependencies:
    - containers
    - parsec

executables:
  d01: &base-exe
    source-dirs: exe
    main: d01.hs
    dependencies: advent-of-code-y2021
  d02:
    <<: *base-exe
    main: d02.hs
  d03:
    <<: *base-exe
    main: d03.hs
  d04:
    <<: *base-exe
    main: d04.hs
  d05:
    <<: *base-exe
    main: d05.hs
